/cdap/nonsensitive/account/security_events_slack_renotify_after_days: 30
/cdap/nonsensitive/account/security_events_slack_severity_list: CRITICAL,HIGH,MEDIUM
/cdap/sensitive/account/security_events_slack_webhook_url: ENC[AES256_GCM,data:z9MLEAlb76u6MZ+GWcWcfnRtax1J677k47tabDmwCqAGN7H2BrmTnkIs1fAhl9dShaL5qZrq78s0sY9b2hCAGIWWaUenVbGGpWBuZvh7rw==,iv:kbgCH76ryIbnU40SWd/Wgg+hULSgGsTO4LLWIPoDE68=,tag:NmwrTB/oVI0WEhL9R5eV2g==,type:str]
/cdap/sensitive/bucket-access-logs-bucket: ENC[AES256_GCM,data:TjwtktvWlh7Gt7JrTuxZganUT3AotzmEAeYKkpn5GutLcIT1/KSpTV1kjMxV,iv:fSMld0pXjqKabcq+8CK7kG018tspwVAS30ngYFepJKw=,tag:dMsUtxHVSpiHb9U+ebUbNg==,type:str]
/cdap/sensitive/mgmt-vpc/cidr: ENC[AES256_GCM,data:uNKE6Nckt24ZWHDHEWjU,iv:yVvl1HbK7ljy6lgZdGUkfi0CeIHPnd2uof9tVB1z008=,tag:9tQ1atj1Vwkgw6j1FQ8p5w==,type:str]
/cdap/sensitive/mgmt/public_nat_ipv4/cdap-east-mgmt-a: ENC[AES256_GCM,data:sL/7GoM3BjiBN0Wt1Xg=,iv:vxDF8a1nduKPkjNGjxFai/oLi9NrO5F2fzdbjZ9OC+w=,tag:iKQYgyBHaZqTnVKd2L6UcQ==,type:str]
/cdap/sensitive/mgmt/public_nat_ipv4/cdap-east-mgmt-b: ENC[AES256_GCM,data:3T3XJXAfO+ukonOB,iv:pRRz120EXNn3Mjp+MWmjybWk20Tiqt5mZyH9tCt06FI=,tag:ejOONP6IvUWMfQUMotshcw==,type:str]
/cdap/sensitive/mgmt/public_nat_ipv4/cdap-east-mgmt-c: ENC[AES256_GCM,data:FqJ5g/NEdjs9VUW1,iv:gPMZEY94Th2seM4bg6axdVKyD8ZS4y6EUjt92spY0nk=,tag:dM7vk5x4WRZd1/iC96LOjg==,type:str]
/cdap/sensitive/sonarqube/token: ENC[AES256_GCM,data:zdaR2Lys9SNIsYVM/H+jBY9LYzefdhwPZm9O6zseZHlm6DOmDACxEJnHGik=,iv:fqiYm6LQARMFrOvuXC924SXzFlaGLQ3UnNCWY8hwp10=,tag:eb3/7+NF61G5BTdp4/QxLQ==,type:str]
/cdap/nonsensitive/sonarqube/url: https://sonarqube.cloud.cms.gov
/cdap/sensitive/artifactory/password: ENC[AES256_GCM,data:zOG+FAY+EOGupfxwYXBZNc37qStdeEqn65wgnEaR84ww7BJXbgdM+Fhl9FXKqNOSqDs2O8AEx7Ao/tIIWS3EUA==,iv:+4nqU3fK1uYc2TOFyPMtkuKvXuMFhz9bUmsFbbRSUHM=,tag:i7Wd5CxlTF9MxPowXuPfog==,type:str]
/cdap/nonsensitive/artifactory/url: https://artifactory.cloud.cms.gov/artifactory
/cdap/nonsensitive/artifactory/user: ab2d-bcda-dpc-plt
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:${ACCOUNT_ID}:key/e32dffdb-97e7-4b64-b5cb-f6dc4e6fabca
      created_at: "2025-10-03T17:27:53Z"
      enc: AQICAHiXhc+HhELIyRKOpc5vBWQJB9/2XFW+CxWFIfUyci0r/wGkXSt3AG0b8bCJ0pVuEmyuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+S5DlWnhTDkMvmOxAgEQgDvMXlly/I5Vb2ah1KX2fSbY3mMOxA92rK4MU/rsyUN2oR8WXebzzW+ooNY1pEdGE4FMUmLUrU5qbcUoPg==
      aws_profile: ""
  unencrypted_regex: /nonsensitive/
  mac_only_encrypted: true
  version: 3.11.0
