/cdap/${env}/common/nonsensitive/artifactory/url: https://artifactory.cloud.cms.gov/artifactory
/cdap/${env}/common/nonsensitive/artifactory/user: ab2d-bcda-dpc-plt
/cdap/${env}/common/nonsensitive/security-events/renotify-after-days: 30
/cdap/${env}/common/nonsensitive/security-events/severity-list: CRITICAL,HIGH,MEDIUM
/cdap/${env}/common/nonsensitive/sonarqube/url: https://sonarqube.cloud.cms.gov
/cdap/${env}/common/sensitive/artifactory/password: ENC[AES256_GCM,data:O87T1Y7qQNbEytR3pG1K7pHVX8F7OEz2CZ+0Uo/E2E1XNb6PSs9iAVnROC9Mio3uv9KRNHdWxt6wytfcil0JyA==,iv:lOneSA9kmP6ycjsXDb1PTBwTEmw0+svXk1ksQ5kP8oQ=,tag:tdAqOs6oTvgCg9DPsf/g1Q==,type:str]
/cdap/${env}/common/sensitive/security-events/webhook-url: ENC[AES256_GCM,data:o7UVib5gThT48CJ8tyTPMUHzVFHqb/xP1tW9zI5ENGV1OlQrqTI0f18/Mfommm9KP7HfHGA3Z0XdtgoJ22DUBNPiRoNm5nwXWaSvrhZvlA==,iv:fWwjDLnbfsNek8kRdCVSQ37pNpH4gTaoWLnqtdmTyiE=,tag:dMFzHbiWtKa5d+0d31OaPQ==,type:str]
/cdap/${env}/common/sensitive/sonarqube/token: ENC[AES256_GCM,data:eZucMWrzVWvl2q9cwCRXQfv809VF+ZTSFPthaTAX6yuZxrkmNkLqkKtiWCM=,iv:KQnKCOfRf4nfmhT4qrhUuFlmZqrC2DuhXSgVaxuYf4c=,tag:3q328+okWudtm6/7LTiSGQ==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:${ACCOUNT_ID}:alias/cdap-prod
      created_at: "2026-01-12T15:41:07Z"
      enc: AQICAHhFK5WpttutkcboPynMViVnpNPMGZugCZIggQQtL9bdTQEVc7aw0Dj/CJQVlpM/eSyPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3F5iEguM2hXz9f/iAgEQgDtXiU6GxFA32Xslvj1R8w+TaGC1UvYtc3rdlg49JU/xJLt/LpnXoBRD3Yfqqj3xyx33KdbhAD623ooF9Q==
      aws_profile: ""
    - arn: arn:aws:kms:us-west-2:${ACCOUNT_ID}:alias/cdap-prod
      created_at: "2026-01-12T15:41:07Z"
      enc: AQICAHiMFrJFiUnwYvJXakJHJWqEMy1v6tkF0T1GwxO2Rp9u8wEFdRMn/TTetpUqYnY2ejpkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMq8fSnFvcU1+8hIlrAgEQgDvFXLUTojxRKoHnruqy+moh58mk//npBqXdIZAAE5U4kUIwhUniitWHJ8zOptpAmwik1UMcH6ScXKJKBA==
      aws_profile: ""
  unencrypted_regex: /nonsensitive/
  mac_only_encrypted: true
  version: 3.11.0
