/cdap/${env}/common/nonsensitive/artifactory/url: https://artifactory.cloud.cms.gov/artifactory
/cdap/${env}/common/nonsensitive/artifactory/user: ab2d-bcda-dpc-plt
/cdap/${env}/common/nonsensitive/security-events/renotify-after-days: 30
/cdap/${env}/common/nonsensitive/security-events/severity-list: CRITICAL,HIGH,MEDIUM
/cdap/${env}/common/nonsensitive/sonarqube/url: https://sonarqube.cloud.cms.gov
/cdap/${env}/common/sensitive/artifactory/password: ENC[AES256_GCM,data:SZa8idYpvSJUN9yw1XRU/9CcK6DL/IXpOySR54wEwTpeiV6Gh7p/a7iYpWjfDlMGgt3i/ridi2W6IftyU7SvYQ==,iv:tA2KGOkVdDZgx8b/VUOYH0pn7wVB4eioWAWSqOXsmQ8=,tag:aoaRoV9I9zwQLIQBN9oWVA==,type:str]
/cdap/${env}/common/sensitive/security-events/webhook-url: ENC[AES256_GCM,data:S0om15B8fV4Hre2kT0XBCqhwW/H/vVCZAswMQdZEIKl/1bXD6TgcOjwTShgwijDwQP8qd00YRmgEgQR63qUQMgv/ruTrSQjH8V/QEQdZeQ==,iv:bZ7T5+cvOq0UiuMbCQeDzlATyMwMWRV9uDnovscKO50=,tag:gMHQWZkM8ccWT9C5Lv13Hw==,type:str]
/cdap/${env}/common/sensitive/sonarqube/token: ENC[AES256_GCM,data:MjWtAsjfPxxA+WBtVaJTv2Iuz4nPa2Q/E5W0wZ+52mh01NncP1NTI0VBCto=,iv:VIgTVl/sVsBrKwHN+6YcgxajeIp/e6XzTUJb0ck3aJc=,tag:a1otK8ye7M9Y5bG31RW3HQ==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:${ACCOUNT_ID}:alias/cdap-prod
      created_at: "2026-01-08T20:37:24Z"
      enc: AQICAHhFK5WpttutkcboPynMViVnpNPMGZugCZIggQQtL9bdTQHvAfONj2+nVoQ8gr9edjwnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDirECDDEOE9AGSx1AgEQgDvabcDmFB/t/m2+AS4UvGGu/hD15E6H+puURdRmd2fHgY5XsTr3TXfsqrGM0RqRtM4oUSlmNOq5HzQH2A==
      aws_profile: ""
  unencrypted_regex: /nonsensitive/
  version: 3.11.0
