/bfd/prod/mtls/nonsensitive/public.p12.b64: |
  -----BEGIN CERTIFICATE-----
  MIIFLTCCAxWgAwIBAgIJAOqWW2If8ibEMA0GCSqGSIb3DQEBDAUAMCcxJTAjBgNV
  BAMTHHByb2QuZmhpci5iZmQuY21zY2xvdWQubG9jYWwwHhcNMjUwNTIxMTk0MDQ0
  WhcNMjcwNTIxMTk0MDQ0WjAnMSUwIwYDVQQDExxwcm9kLmZoaXIuYmZkLmNtc2Ns
  b3VkLmxvY2FsMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtUeewY12
  WlwhF1ML9MhUPM7P/Eg7jXEvpkvEcRNbSCuCGg8iTbDIAcLMFnPXBcw6WM5Flt2+
  x/wQUZ/eWLQ2vJCNNvLxZubMYcsUJvm4MNDYUZdAVsMNcmWvJ33jz5aj7IE00OZX
  nRWc1w3vMa8ruO7n1SSOLJ4Jhly4eKIh1GJSjxL6rdvUmvKZKcEj6Vp2mykJ6Dq9
  OHIWpi7TgB6BbpmaFniv6iyiiUmUFfrjgJFk54yjAaT7jM+21Gm5EURQX2KIzf05
  zPpr8wOWqxJVJK2blkfKuZ8V/uTwtbKkmDKjqo7t2ncIaH4/ud4Rwv+nCnFaFP5n
  hLohZMtegnfBl9za9aT34bZ4ItvfXghuPNABbBj1B5rvbJWbXJEnjXAqTqbn2ljW
  QMCkeJgQ8lxbCnlGaVKxJyIEDT4dlrgTdJKKfyTrp0NIrdN43Tw4/ppacPBSSpDu
  irEWoshMnqWKzNxRQblVCCIT0YCLGCle7NTIoxPtlWE1NikQmNLlo8UzxZAuKh6J
  cSgS65SGHjFaIqv34vOqFp8wZPBc0+KAGze358zTJQVA86MpYqzHTBSTXdJHex1A
  VHHUUq42y+5aXbqsvxG9aBiYb5JzVO1r1gp1hi7gEPHxP6KA9okPc6iQWSmItvFf
  XoOaUFycvj/LH+grdzddEQShCvAtW3JFDFMCAwEAAaNcMFowHQYDVR0OBBYEFMtJ
  s33rm4fhXUgMT11nsJ+1wMUkMDkGA1UdEQQyMDCCHHByb2QuZmhpci5iZmQuY21z
  Y2xvdWQubG9jYWyCEHByb2QuYmZkLmNtcy5nb3YwDQYJKoZIhvcNAQEMBQADggIB
  AJh+TWyhUTWS+YWBhgn36DMu7E+H/mpMusBx1yXUHV04nAJ9Euea1pcX/igDz5Vn
  rWYlj+Kkf+MFB8Ecc/lN9t0v5a33SSxOvhL2hdusMwgPKVoFGfc+QZMa7VsQgqOp
  vugebonx3Xyc8QsQcxFNCD+TOO5iSdUOh8RtMES9Y2RWaMvoSnMk/t29lW8KFECj
  l2TC8zwxYlPW07++mH3h3gdwUoU3JoQ210ny+uKeC2zo+qMv3F/bXZ+ad51rzWAo
  vPCFHMfq2URwpPyOG3czKl74WJAurm78OyaVDem83xJem/XDnMrRvDPzEkcG19LA
  aheKKIC/sryWugwQJx7WaVCPjJA3eBHeViq6gRL+NvqLhNxteBNJK4Wf3S8UfYxC
  NFeVQPbpvqBxO8JJtMhMUD3y6TVZp5RpVlaLfA9BZd6axFfTYm4e0iT0ORVRI3OU
  Ri+iH4wmi19bn0o6+VeNDne1HPx9xbqfze2/qEaCcNESYdUnauMbtW1jAnD1uNtZ
  2F/4F5tqG84dTKGijtWJg8nyefZCmaBeJZi2W639VlVOv5uY1KOLrGW0cM0o8JKk
  WcHj/BVCcYGJtwBKbWIuNZLRsV7UGLSFKPPjT5GoXk7WqMUvu+pTabVpj7bwyRU+
  a6VzzftJOQBO4kMriNBUC1t3aQfjWjma668WCji9PN6v
  -----END CERTIFICATE-----
/bfd/sandbox/mtls/nonsensitive/public.p12.b64: |
  -----BEGIN CERTIFICATE-----
  MIIFPTCCAyWgAwIBAgIJAKokm3IWN1IAMA0GCSqGSIb3DQEBDAUAMCsxKTAnBgNV
  BAMTIHByb2Qtc2J4LmZoaXIuYmZkLmNtc2Nsb3VkLmxvY2FsMB4XDTI1MDUyMTE5
  NDA0NVoXDTI3MDUyMTE5NDA0NVowKzEpMCcGA1UEAxMgcHJvZC1zYnguZmhpci5i
  ZmQuY21zY2xvdWQubG9jYWwwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
  AQCxtfwy1tlJrHn+nwMTd2ANqkPgE3d+iesQENR+JtSblyobIa0hFxqjQCVoJ8gx
  xmdasXNUjPy/Mwxsf2GRV8tPo8gSz3fYYQAITX4Byp7jMu3yvwK1hEmpGOHm9Mqd
  2YWpGbaT3OxFwW+gyvYFW7ekTIIs5NnuKvj9w8bwIpxayw19dA6gwCtItw6Pr0dV
  pLjL+WcrsWASe5gfTMi6ObY7aHoDbhNzn+5PJisTdSF8HVsNz/rwbKS0sAgCcDHL
  cl9YhJGD+GTatu2u5zK/hw8GlZCzz6dO9ePIEF9Gl3t/SP36YAGxQ2eUNrAOu606
  DGKa7pXxtgHZf1aWKw3wNVj0FHYIjvl9Uriiby4Cz5FsqmbTS12/swxLv6yrrgK/
  9/eLksKd6cvwFlRyGLhpSxv0wozVWExWGqLVPebvtRvsZdF8FQobrRFOzRjk73o5
  ++2ufbaD0B9pFYoMDm5ul5FAQTUdmou5ZZCNJ/dkSyxgY1JlYLBILJgLAZSPbZCl
  OqthUV+BjG9Uyhy9zWSUp8vhjPOtlGtv195rP3ajZ7HMSn0HVt5PCNd4XxXL2mv8
  WPHoAFS+4blJUF8u96wKjxPzSieydKrkoVPopYIgfKUbroivMUhQRsY3t591EtAW
  rVTGkFSv43tSox44DgGSOaLBbM5vTaO0GAdhLUDQE7qoqQIDAQABo2QwYjAdBgNV
  HQ4EFgQUSA1GjmplpMpQxTol17CAG/MCDPIwQQYDVR0RBDowOIIgcHJvZC1zYngu
  Zmhpci5iZmQuY21zY2xvdWQubG9jYWyCFHByb2Qtc2J4LmJmZC5jbXMuZ292MA0G
  CSqGSIb3DQEBDAUAA4ICAQA18y+iKgHncEGW0R9E175inMwyHszVAe3uaD9eq/xt
  amormagDs21FJSL1Aul/acrzdzuGPgLTUntsnFRBExz/cDdj9mVzzqHmZq4Ph/z5
  aS6ugYMWmEps5XJpDHplSDiUqufqSnlzDp+0MKj8MyqPPKX+76ABMO5HpoIxszfI
  GwctAJMT/8nvCCh1k8dwDoUpQBqrXNin1dAzdHkcX/dyHK2QpBCJBPobKmM7AGNL
  UuI2xbWgdnt/ZfBqa1DhomMIt39+FsIgbi6YKgsM9tSxTIeC5Ow2eZM1JC8oqgQi
  O/6/8kiPmHV3bnjKdsY5LjGb6mqvVBB1oUMRtykJh2VA4aDvGa1FKBqK0S8yiQvI
  CJ7HV0qVdjkSSCgdIUodP+bFT6qJEylzWXfNkdKeIKxaMEdcCHpaLpWU2hL/WxYX
  82FJa1jWmSO9bp+frpslIO+tbj8eyp8P3x+c5ydEOh7wAwBJxYOOT2d84iNuMCCH
  AjegSpE6Y6tIraWXAWUlddkXZuP0u6kvzO+tBqHam4+eKtde3B12yPkiels66d6O
  PeX5zhchW9mBRK1ckfWLIzlH6gNomUHVHq9uhlHT2N8CjcC+65Ip4cAuZlFJKLkF
  wSBGLqRCSaB3KO1l0bsF+QqI9PD77es2g1dobi74Oc553pxNFLr/pXkjEn7hrizu
  Rg==
  -----END CERTIFICATE-----
/cdap/${env}/common/nonsensitive/artifactory/url: https://artifactory.cloud.cms.gov/artifactory
/cdap/${env}/common/nonsensitive/artifactory/user: ab2d-bcda-dpc-plt
/cdap/${env}/common/nonsensitive/security-events/renotify-after-days: 30
/cdap/${env}/common/nonsensitive/security-events/severity-list: CRITICAL,HIGH,MEDIUM
/cdap/${env}/common/nonsensitive/sonarqube/url: https://sonarqube.cloud.cms.gov
/cdap/${env}/common/sensitive/artifactory/password: ENC[AES256_GCM,data:O87T1Y7qQNbEytR3pG1K7pHVX8F7OEz2CZ+0Uo/E2E1XNb6PSs9iAVnROC9Mio3uv9KRNHdWxt6wytfcil0JyA==,iv:lOneSA9kmP6ycjsXDb1PTBwTEmw0+svXk1ksQ5kP8oQ=,tag:tdAqOs6oTvgCg9DPsf/g1Q==,type:str]
/cdap/${env}/common/sensitive/security-events/webhook-url: ENC[AES256_GCM,data:o7UVib5gThT48CJ8tyTPMUHzVFHqb/xP1tW9zI5ENGV1OlQrqTI0f18/Mfommm9KP7HfHGA3Z0XdtgoJ22DUBNPiRoNm5nwXWaSvrhZvlA==,iv:fWwjDLnbfsNek8kRdCVSQ37pNpH4gTaoWLnqtdmTyiE=,tag:dMFzHbiWtKa5d+0d31OaPQ==,type:str]
/cdap/${env}/common/sensitive/sonarqube/token: ENC[AES256_GCM,data:eZucMWrzVWvl2q9cwCRXQfv809VF+ZTSFPthaTAX6yuZxrkmNkLqkKtiWCM=,iv:KQnKCOfRf4nfmhT4qrhUuFlmZqrC2DuhXSgVaxuYf4c=,tag:3q328+okWudtm6/7LTiSGQ==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:${ACCOUNT_ID}:alias/cdap-prod
      created_at: "2026-01-12T15:41:07Z"
      enc: AQICAHhFK5WpttutkcboPynMViVnpNPMGZugCZIggQQtL9bdTQEVc7aw0Dj/CJQVlpM/eSyPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3F5iEguM2hXz9f/iAgEQgDtXiU6GxFA32Xslvj1R8w+TaGC1UvYtc3rdlg49JU/xJLt/LpnXoBRD3Yfqqj3xyx33KdbhAD623ooF9Q==
      aws_profile: ""
    - arn: arn:aws:kms:us-west-2:${ACCOUNT_ID}:alias/cdap-prod
      created_at: "2026-01-12T15:41:07Z"
      enc: AQICAHiMFrJFiUnwYvJXakJHJWqEMy1v6tkF0T1GwxO2Rp9u8wEFdRMn/TTetpUqYnY2ejpkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMq8fSnFvcU1+8hIlrAgEQgDvFXLUTojxRKoHnruqy+moh58mk//npBqXdIZAAE5U4kUIwhUniitWHJ8zOptpAmwik1UMcH6ScXKJKBA==
      aws_profile: ""
  unencrypted_regex: /nonsensitive/
  mac_only_encrypted: true
  version: 3.11.0
