/cdap/nonsensitive/account/security_events_slack_renotify_after_days: 30
/cdap/nonsensitive/account/security_events_slack_severity_list: CRITICAL,HIGH,MEDIUM
/cdap/sensitive/account/security_events_slack_webhook_url: ENC[AES256_GCM,data:J70QSI23I0d1OnvD+n2ncd/ii0XiZ3NRcQqVwCLCBd7UxRIKgJ1YWqCZ9xV2Y8s/4fy+hi8iVvIkd0WdnC1Q9Adwh2rvRKKWM6lS59EYlA==,iv:/ZIY4WGOsxo2pR/t2FYADYcUeEq5eutP43KkNeTa3q0=,tag:HYuxPAStpJZ0t39j/xHLYg==,type:str]
/cdap/sensitive/bucket-access-logs-bucket: ENC[AES256_GCM,data:I8m2zMO44IB1FnAuK08G99390eF5NjLcKTVvY4T5oD2O6/Apt3oSV3GAUldn,iv:DQUyoHG1Gplx4YuogWcG9kZnK3XTZXC+N5Ayzyb6LDM=,tag:wQpSTHVaItOGb3PC6tHw/w==,type:str]
/cdap/sensitive/mgmt-vpc/cidr: ENC[AES256_GCM,data:bKqvpJcIqTqG9DkzO1/T,iv:ul/XIzIZ3BnERohYmuM7fWXWTYI0b45T4F2lUFHkvIw=,tag:LEpy1QiHUoGlTg+mKUaQtg==,type:str]
/cdap/sensitive/gmt/public_nat_ipv4/cdap-east-mgmt-a: ENC[AES256_GCM,data:+mOA32KHMukav+YrGiI=,iv:XsU4F/UvJIlvwgco+SssgdMIEKyKx1e+AwfWP+bheYE=,tag:PsplAE2eFcxWvPddXNHEdQ==,type:str]
/cdap/sensitive/mgmt/public_nat_ipv4/cdap-east-mgmt-b: ENC[AES256_GCM,data:yrLn9ruTYs3iUGtQ,iv:Sbvhi8ByvNKxq6HiI4sBYZ/J2z3baL6xtCqNwO+QBRo=,tag:cAAvVVyTZe7EC5nMOH7MYg==,type:str]
/cdap/sensitive/mgmt/public_nat_ipv4/cdap-east-mgmt-c: ENC[AES256_GCM,data:SR+94ef0AuGMEzGP,iv:sbYtwbP3LFByLYzQysND27FDmSbqP7ihT+qXgqSuEds=,tag:UHJhmmOhBQ/7XsUHsLkkpA==,type:str]
/cdap/sensitive/sonarqube/token: ENC[AES256_GCM,data:8Vu/Q9Xb9F2r43Xi2qDvrbOwEl1dOQCDaZAQchZdjbiqiUbdCM/ZUHM1Xiw=,iv:Vc8u7xoaAY4jiwN8/hlIA0fP5GpH4iWbWt+E5a2Bxjk=,tag:Klucyv8omHZz9yAcy/D3SQ==,type:str]
/cdap/nonsensitive/sonarqube/url: https://sonarqube.cloud.cms.gov
/cdap/sensitive/artifactory/password: ENC[AES256_GCM,data:IRxXjLkc9U04LGlDdaFeGjLQjvqRhdgDzMD4LuQObpS30tFgfHcgQxUEH/ZfYHxo7+P8YWRa+H7A+5qnmprLow==,iv:TMdVDwurOwV6PakCthdzDLQU9rtChiYH95Cstk3qiNw=,tag:ZUT0Av6p93lnUYXo83+Mng==,type:str]
/cdap/nonsensitive/artifactory/url: https://artifactory.cloud.cms.gov/artifactory
/cdap/nonsensitive/artifactory/user: ab2d-bcda-dpc-plt
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:${ACCOUNT_ID}:key/e32dffdb-97e7-4b64-b5cb-f6dc4e6fabca
      created_at: "2025-10-03T17:38:55Z"
      enc: AQICAHiXhc+HhELIyRKOpc5vBWQJB9/2XFW+CxWFIfUyci0r/wGgF/ZOMV/LMrvJSRhtedM1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8xXrZN9mTFGkvKjtAgEQgDsOpxt5mGlXEpdiTlnAjnt/AcOMpA8coSH4NHWfC2Tsw/VES55XVAaWQYXuOOdKnIJznMlUqzqBVrfvTw==
      aws_profile: ""
  unencrypted_regex: /nonsensitive/
  version: 3.11.0
