name: tf-config
run-name: tf-config ${{ (inputs.apply || (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'schedule') && 'apply' || 'plan' }}

on:
  push:
    paths:
      - .github/workflows/tf-config.yml
      - terraform/services/config/**
  schedule:
    - cron: "12 14 * * 1-5"
  workflow_dispatch:
    inputs:
      apply:
        required: false
        type: boolean
        description: "Apply the terraform?"

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    working-directory: ./terraform/services/config

jobs:
  check-fmt:
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2
      - uses: cmsgov/cdap/actions/setup-tenv@8343fb96563ce4b74c4dececee9b268f42bd4a40
      - run: tofu fmt -check -diff -recursive .
  plan-apply:
    needs: check-fmt
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    strategy:
      fail-fast: false
      matrix:
        app: [cdap]
        env: [mgmt]
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2
      - uses: cmsgov/cdap/actions/setup-tenv@8343fb96563ce4b74c4dececee9b268f42bd4a40
      - uses: cmsgov/cdap/actions/setup-yq@328406d6e1d435b4e3da598bcdab22e576c3945e
      - uses: cmsgov/cdap/actions/setup-sops@84a6bcee5b70d63c44f8fec4f9b542cb5ec29a54
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ contains(fromJSON('["dev", "test"]'), matrix.env) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT }}:role/delegatedadmin/developer/${{ matrix.app }}-${{ matrix.env }}-github-actions
          aws-region: ${{ vars.AWS_REGION }}
      - run: tofu init -backend-config=../../backends/${{ matrix.app }}-${{ matrix.env }}.s3.tfbackend
      - run: tofu plan -out=tf.plan
        env:
          TF_VAR_app: ${{ matrix.app }}
          TF_VAR_env: ${{ matrix.env }}
      - if: inputs.apply || (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'schedule'
        run: tofu apply -auto-approve tf.plan
